app.py
from flask import Flask, render_template
from routes import pages


app = Flask(__name__)
app.register_blueprint(pages)


@app.errorhandler(404)
def page_not_found(err):
    return render_template("404.html"), 404


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)

main.py
import argparse
import os

import flask
import flask_login
import jinja2

from blog import editor
from blog import login
from blog import pages
from blog import util


app = flask.Flask(__name__)
app.register_blueprint(pages.pages)
app.register_blueprint(login.login_pages)
app.register_blueprint(editor.editor_pages)
app.jinja_env.globals["fdate"] = util.js_format_datetime

login_manager = flask_login.LoginManager()
login_manager.init_app(app)
login_manager.login_view = "login_pages.login_page"

# Development settings
app.config.update(
    DEBUG = True,
    APPLICATION_ROOT = "/",
    SECRET_KEY = b"TheNotSoSecretDevKey"
)

# Overwrite default dev settings with production settings.
# You must make sure this file is *not* checked into git!
app.config.from_pyfile("config.cfg", silent=True)


# Generic top-level 404, needed since the pages routes only
# handle 404 errors within the pages blueprint itself
@app.errorhandler(404)
def page_not_found(err):
    return flask.render_template("404.html"), 404


@login_manager.user_loader
def user_loader(user_id):
    return login.load_user(user_id)


if __name__ == "__main__":
    app.jinja_env.auto_reload = True
    app.run(host="0.0.0.0", port=5000)

routes.py
from datetime import datetime

from flask import Blueprint, redirect, url_for
from flask import render_template, request, abort
import flask_login
from sqlalchemy.sql.expression import func
from werkzeug.contrib.atom import AtomFeed

import database as db


pages = Blueprint("pages", __name__, template_folder="templates", static_folder="static")


@pages.route("/")
def index_page():
    with db.session_context() as session:
        posts = session.query(db.Post).order_by(db.Post.published.desc()).limit(10)

        if posts.count() == 0:
            return render_template("index.html")

        tags = session.query(db.Tag).join(
            db.Post2Tag, db.Tag.rowid == db.Post2Tag.tag_id).filter(
                db.Post2Tag.post_id == posts[0].rowid).all()
        return render_template("index.html", post=posts[0], older_posts=posts, tags=tags)


@pages.route("/post/id/<int:post_id>")
def post_page(post_id):
    with db.session_context() as session:
        post = session.query(db.Post).get(post_id)
        posts = session.query(db.Post).order_by(db.Post.published.desc()).limit(10)
        tags = session.query(db.Tag).join(
            db.Post2Tag, db.Tag.rowid == db.Post2Tag.tag_id).filter(
                db.Post2Tag.post_id == post_id).all()
        if post is None:
            abort(404)
        return render_template("post.html", post=post, older_posts=posts, tags=tags)


@pages.route("/post/new")
@flask_login.login_required
def new_post_page():
    with db.session_context() as session:
        max_id = session.query(func.max(db.Post.rowid)).scalar()
        return redirect(url_for("pages.new_post_id_page", new_id=max_id+1))


@pages.route("/post/new/<int:new_id>", methods=["GET", "POST"])
@flask_login.login_required
def new_post_id_page(new_id):
    if request.method == "GET":
        post_data = { 
            "title": "New Post",
            "text": "# New post\n\nEnter a new post here...",
            "published": datetime.utcnow() 
        }
        post = db.Post(**post_data)
        return render_template("editor.html", post=post, enable_save=True)

    post_data = { 
        "title": request.form["title"],
        "text": request.form["post"],
        "published": datetime.utcnow() 
    }

    with db.session_context() as session:
        post = db.Post(**post_data)
        session.add(post)
    return render_template("editor.html", post=post, post_saved=True)


@pages.route("/feed")
def feed_page():
    with db.session_context() as session:
        posts = session.query(db.Post).order_by(db.Post.published).limit(10)
        feed = AtomFeed(title="Recent Posts", feed_url=request.url, url=request.url_root)

        for post in posts:
            updated = post.published if post.last_modified is None else post.last_modified
            feed.add(post.title, post.html, content_type="html",
                    url="{0}/post?id={1}".format(request.url_root, post.rowid),
                    updated=updated, published=post.published)

        return feed.get_response()


@pages.route("/archive")
@pages.route("/archive/tag/<string:tag>")
def archive_page(tag=None):
    with db.session_context() as session:
        if tag:
            posts = session.query(db.Post).join(
                db.Post2Tag, db.Post.rowid == db.Post2Tag.post_id).join(
                    db.Tag, db.Tag.rowid == db.Post2Tag.tag_id).filter(
                        db.Tag.tag == tag).all()
            if not posts:
                abort(404)
        else:
            posts = session.query(db.Post).order_by(db.Post.published).all()
        tags = session.query(db.Tag).all()
        return render_template("archive.html", tags=tags, posts=posts, tag_filter=tag)


@pages.route("/about")
def about_page():
    return render_template("about.html")


@pages.errorhandler(404)
def page_not_found(err):
    return render_template("404.html"), 404

templates/about.html
{% extends "layout.html" %}

{% block header %}
    <h1>About Me</h1>
{% endblock %}
            
{% block content %}
    <h2>There is nothing here yet!</h2>
{% endblock %}

{% block infobar %}
{% endblock %}

templates/archive.html
{% extends "layout.html" %}

{% block header %}
    <h1>Archive</h1>
{% endblock %}
            
{% block content %}
    <h2>All Posts {% if tag_filter %} with Tag '{{ tag_filter }}' {% endif %} </h2>
    <ul>
        {% for post in posts %}
            <li>
                <div class="archive-row">
                <div class="post-link">
                    <a href="{{ url_for('.post_page', post_id=post.rowid) }} ">{{ post.title}}</a>
                    <div class="published">
                        {{ fdate(post.published) }}
                    </div>
                </div>
                {% if current_user.is_authenticated %}
                <div class="edit-delete-links">
                    <a class="edit-link" href="{{ url_for('editor.edit_post_page', post_id=post.rowid) }}">edit</a> |
                    <a class="delete-link" href="{{ url_for('editor.delete_post_page', post_id=post.rowid) }}">delete</a>
                </div>
                {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>
    {% if current_user.is_authenticated %}
        <a id="new-post-link" href="{{ url_for('editor.new_post_page') }}">New Post</a>
    {% endif %}
{% endblock %}

{% block infobar %}
    <ul>
        <li><h3>All Tags</h3></li>
        {% for tag in tags %}
            <li>
                <div class="tag-row">
                    <div class="tag-link">
                        <a href="{{ url_for('.archive_page', tag=tag.tag) }}">{{ tag.tag }}</a>
                    </div>
                    {% if current_user.is_authenticated %}
                    <div class="edit-delete-links">
                        <a class="delete-link" href="{{ url_for('editor.delete_tag_page', tag_id=tag.rowid) }}">delete</a>
                    </div>
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/editor.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>justacid.com: blog</title>

    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Proza+Libre|Open+Sans" rel="stylesheet">

    <link href="{{ url_for('static', filename='editor.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='preview-code-styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='favicon.ico') }}" rel="shortcut icon" type="image/x-icon">

    <script type="text/javascript" src="{{ url_for('static', filename='index.bundle.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='editor.bundle.js') }}"></script>
</head>
<body>
{% if post_saved %} <div id="post-saved">Post was saved!</div> {% endif %}
    <div id="grid">
        <div id="header">
             <div id="logo">
                <a href="{{ url_for('pages.index_page') }}"> 
                    <img src="{{ url_for('static', filename='logo.png') }}"/>
                </a>
            </div>
            <a href="{{ url_for('pages.index_page') }}">.jblog - editor</a>
        </div>
        <div id="edit">
            <form method="POST" autocomplete="off">
                <textarea rows="1" cols="1" name="tags" id="edit-tags" placeholder="Tag1, Tag2">{{ tags }}</textarea>
                <textarea rows="1" cols="1" name="title" id="edit-title">{{ post.title }}</textarea>
                <textarea rows="1" cols="1" name="post" id="edit-text">{{ post.text }}</textarea>

                {% if enable_save %}
                <input id="edit-save" type="submit" name="submit" value="Save"/>
                {% endif %}
            </form>
        </div>
        <div id="preview">
            <div id="preview-title"></div>
            <div class="published">Published: {{ fdate(post.published) }}</div>
            {% if post.last_modified %}
                <div class="last-modified">Last Modified: {{ fdate(post.last_modified) }}</div>
            {% endif %}
            <div id="preview-markdown">
            </div>
        </div>
    </div>
</body>
</html>

templates/index.html
{% extends "layout.html" %}

{% block sidebar %}
    {{ super() }}
    {% if post %}
        <div class="toc">
            <h3>Table of Contents</h3>
            {{ post.toc|safe }}
        </div>
    {% endif %}
{% endblock %}

{% block header %}
    {% if post %}
        <h1>{{ post.title }}</h1>
    {% else %}
        <h1>No Posts</h1>
    {% endif %}
{% endblock %}
            
{% block content %}
    {% if post %}
        <div class="published">Published: {{ fdate(post.published) }}</div>
        {% if post.last_modified %}
            <div class="last-modified">Last Modified: {{ fdate(post.last_modified) }}</div>
        {% endif %}
        {{ post.html|safe }}
    {% else %}
        <h2>Nothing. Nada. Zilch.</h2>
        There are no posts yet. Maybe come back later?
    {% endif %}
{% endblock %}

{% block infobar %}
    <ul>
        <li><h3>Tags</h3></li>
        {% for tag in tags %}
            <li><a href="{{ url_for('.archive_page', tag=tag.tag) }}">{{ tag.tag }}</a></li>
        {% endfor %}
    </ul>

    <ul>
        <li><h3>Older Posts</h3></li>
        {% for post in older_posts %}
            <li><a href="{{ url_for('.post_page', post_id=post.rowid) }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/layout.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>justacid.com: blog</title>

    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Proza+Libre|Open+Sans" rel="stylesheet">

    <link href="{{ url_for('static', filename='styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='code-styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='favicon.ico') }}" rel="shortcut icon" type="image/x-icon">

    <link rel="alternate" type="application/atom+xml" title="justacid.com: blog" href="{{ url_for('pages.feed_page') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='index.bundle.js') }}"></script>
</head>
<body>
    <div id="grid-container">
        <div id="logo-container">
            <div id="logo">
                <a href="{{ url_for('pages.index_page') }}"> 
                    <img src="{{ url_for('static', filename='logo.png') }}"/>
                </a>
            </div>
            <a id="home-link" href="{{ url_for('pages.index_page') }}">.jblog</a>
        </div>
        <div id="header">
            {% block header %}{% endblock %}
        </div>
        <div id="sidebar-container">
            {% if current_user.is_authenticated %}
            <div id="login-status">
                Logged in as '{{ current_user.username}}' <a href="{{ url_for('login_pages.logout_page') }}">(logout)</a>.
            </div>
            {% endif %}
            <div id="sidebar">
                {% block sidebar %}
                    <div class="navi">
                        <h3>Links</h3>
                        <ul>
                            <li><a href="{{ url_for('pages.archive_page') }}">Archive</a></li>
                            <li><a href="{{ url_for('pages.about_page') }}">About</a></li>
                        </ul>
                    </div>
                {% endblock %}
            </div>
        </div>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="infobar">
            {% block infobar %}{% endblock %}
        </div>
    </div>
</body>
</html>

templates/login.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>justacid.com: login</title>

    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Proza+Libre|Open+Sans" rel="stylesheet">
    <link href="{{ url_for('static', filename='login-styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='favicon.ico') }}" rel="shortcut icon" type="image/x-icon">
</head>
<body>
    <div id="content">
        <div id="header">
            <h1><a href="{{ url_for('pages.index_page') }}">.jblog Login</a></h1>
        </div>
        {% if login_failed %}
            <div id="login-status">
                Invalid login credentials.
            </div>
        {% endif %}
        <div id ="form">
            <form method="POST">
                <div class="row">
                    <label>username:</label>
                    <input type="text" name="username" id="username"/>
                </div>
                <div class="row">
                    <label>password:</label>
                    <input type="password" name="password" id="password"/>
                </div>
                <div class="row">
                    <input id="login-button" type="submit" name="submit"/>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

templates/post.html
{% extends "layout.html" %}

{% block sidebar %}
    {{ super() }}
    <div class="toc">
        <h3>Table of Contents</h3>
        {{ post.toc|safe }}
    </div>
{% endblock %}

{% block header %}
    <h1>{{ post.title }}</h1>
{% endblock %}
            
{% block content %}
    <div class="published">Published: {{ fdate(post.published) }}</div>
    {% if post.last_modified %}
        <div class="last-modified">Last Modified: {{ fdate(post.last_modified) }}</div>
    {% endif %}
    {{ post.html|safe }}
{% endblock %}

{% block infobar %}
    <ul>
        <li><h3>Tags</h3></li>
        {% for tag in tags %}
            <li><a href="{{ url_for('.archive_page', tag=tag.tag) }}">{{ tag.tag }}</a></li>
        {% endfor %}
    </ul>

    <ul>
        <li><h3>Older Posts</h3></li>
        {% for post in older_posts %}
            <li><a href="{{ url_for('.post_page', post_id=post.rowid) }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}